// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPhZVDY0YJjn1wiBjISM-oJqpToPMBatk',
    appId: '1:503974637196:android:6bda446a9d2415c10115a9',
    messagingSenderId: '503974637196',
    projectId: 'asu-carpooling-flutter',
    databaseURL: 'https://asu-carpooling-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'asu-carpooling-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5yBMwjGB5eyJdX1I90G4kLvZduxqEAVc',
    appId: '1:503974637196:ios:01cecba3f80e5b1c0115a9',
    messagingSenderId: '503974637196',
    projectId: 'asu-carpooling-flutter',
    databaseURL: 'https://asu-carpooling-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'asu-carpooling-flutter.appspot.com',
    iosBundleId: 'com.example.carpoolDriverFlutter',
  );
}
